version: "3.7"

services:

  food-delivery-db:
    image: mongo:4.4.10 
    restart: always
    container_name: food-delivery-db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: food-delivery-db 
    volumes:
      - food-delivery-db:/data/db
    networks: 
      - food-delivery-network

  food-delivery-app:
    image: thisk8brd/food-delivery-app:dev
    build: 
      context: .
      target: dev
    container_name: food-delivery-app
    restart: always
    volumes: 
      - .:/app
    ports:
      - "5000:5000"
      - "3000:3000"
    depends_on:
      - food-delivery-db
    environment:
      - MONGODB_URI=mongodb://food-delivery-db/
    networks: 
      - food-delivery-network


volumes: 
  food-delivery-db:
    name: food-delivery-db

networks: 
  food-delivery-network:
    name: food-delivery-network
    driver: bridge