name: Deployon:
  push:
    branches:
      - masterjobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "food-dv"
          heroku_email: "faicaleljabli77@gmail.com"
          usedocker: true
